//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchetEntities : DbContext
    {
       
        
            public static UchetEntities _context;
            public UchetEntities()
                : base("name=UchetEntities")
            {

            }
            public static UchetEntities GetContext()
            {
                if (_context == null)
                    _context = new UchetEntities();
                return _context;
            }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Оборудование> Оборудование { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<ПользовательОборудование> ПользовательОборудование { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<СостояниеОборудования> СостояниеОборудования { get; set; }
        public virtual DbSet<История> История { get; set; }
    }
}
