//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class История
    {
        public int КодИстории { get; set; }
        public Nullable<int> КодПользователя { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Действие { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
