//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оборудование
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Оборудование()
        {
            this.ПользовательОборудование = new HashSet<ПользовательОборудование>();
        }
    
        public int КодОборудования { get; set; }
        public string НазваниеОборудования { get; set; }
        public string ТипОборудования { get; set; }
        public string СерийныйНомер { get; set; }
        public Nullable<System.DateTime> ДатаПокупки { get; set; }
        public int КодСостояниеОборудования { get; set; }
        public int КодПоставщика { get; set; }
        public string Местоположение { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        public virtual СостояниеОборудования СостояниеОборудования { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПользовательОборудование> ПользовательОборудование { get; set; }
    }
}
