//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.ПользовательОборудование = new HashSet<ПользовательОборудование>();
            this.История = new HashSet<История>();
        }
    
        public int КодПользователя { get; set; }
        public string ИмяПользователя { get; set; }
        public string Пароль { get; set; }
        public int КодРоли { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public Nullable<int> Телефон { get; set; }
        public string ФамилияПользователя { get; set; }
        public string Логин { get; set; }
    
        public virtual Роли Роли { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПользовательОборудование> ПользовательОборудование { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История> История { get; set; }
    }
}
